version: '3.8'

services:
  # SPRING BOOT API
  backend:
    build: .
    container_name: gscores_api
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/gscores_db?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=rootpass
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      db:
        condition: service_healthy

  # MYSQL DATABASE
  db:
    image: mysql:8.0
    container_name: gscores_db
    environment:
      - MYSQL_DATABASE=gscores_db
      - MYSQL_ROOT_PASSWORD=rootpass
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-prowrootpass"]
      interval: 5s
      timeout: 5s
      retries: 10