spring.application.name=gscores


spring.datasource.url=jdbc:mysql://mysql-gscores-th13nnh.a.aivencloud.com:17629/defaultdb
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_uNSHpyNQPPbhK4peCR_
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
server.port=${PORT:8080}

# PostgreSQL Connection
#spring.datasource.url=jdbc:postgresql://localhost:5432/gscores_db
#spring.datasource.username=postgres
#spring.datasource.password=123456

#spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.jdbc.batch_size=1000
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.show-sql=false 
//

# Keep the app responsive while loading
spring.h2.console.enabled=false


## Connect to in-memory H2 Database
#spring.datasource.url=jdbc:h2:mem:gscoresdb
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=
#
## Tell Spring to automatically create our tables based on our Entity class
#spring.jpa.hibernate.ddl-auto=update
#
## Enable the H2 web console so we can view our data later
#spring.h2.console.enabled=true